### ISSUE TITLE
checkpoint (pretrained model)

### ISSUE THREAD

**Issue by happy-jihye** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#4]
Hello, zhanglonghao1992 
Thank you for you great implementation.

Would you mind providing the pretrained models (checkpoints)? 
Thank you for your help.

Jihye 😊

**Comment by zhanglonghao1992** [comment]
At present, I am trying to train the model on voxceleb2 and other datasets with higher resolutions (e.g. > 512x512). After that, I will choose some  checkpoints with better performance to release.

**Comment by zhanglonghao1992** [comment]
> Hello, ZLH
> Thank you for you great implementation.
> 
> Would you mind providing the pretrained models (checkpoints)?
> Thank you for your help.
> 
> Jihye 😊

At present, I am trying to train the model on voxceleb2 and other datasets with higher resolutions (e.g. > 512x512). After that, I will choose some checkpoints with better performance to release.

**Comment by johndpope** [comment]
I can't get anywhere without that file it seems. 

no checkpoint
```shell


(torch) ➜  One-Shot_Free-View_Neural_Talking_Head_Synthesis git:(main) ✗ python demo.py --config config/vox-256.yaml  --source_image '/home/jp/Desktop/2.jpg'  --driving_video '/home/jp/Documents/gitWorkspace/SimSwap/J11-wm.mp4'  --relative --adapt_scale --find_best_frame 

demo.py:28: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "demo.py", line 282, in <module>
    generator, kp_detector, he_estimator = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, cpu=opt.cpu)
  File "demo.py", line 48, in load_checkpoints
    checkpoint = torch.load(checkpoint_path)
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ''

```

made up check point. (file doesn't exist)
```shell

(torch) ➜  One-Shot_Free-View_Neural_Talking_Head_Synthesis git:(main) ✗ python demo.py --config config/vox-256.yaml --checkpoint ./check.pt --source_image '/home/jp/Desktop/2.jpg'  --driving_video '/home/jp/Documents/gitWorkspace/SimSwap/J11-wm.mp4'  --relative --adapt_scale --find_best_frame

demo.py:28: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "demo.py", line 282, in <module>
    generator, kp_detector, he_estimator = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, cpu=opt.cpu)
  File "demo.py", line 48, in load_checkpoints
    checkpoint = torch.load(checkpoint_path)
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './check.pt'

```

**Comment by zhanglonghao1992** [comment]
I didn‘t provide the pre-trained model，so you have to train the model first to get the checkpoint.





来自钉钉专属商务邮箱------------------------------------------------------------------
发件人：John D. ***@***.***>
日　期：2021年09月05日 01:56:03
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis] checkpoint (pretrained model) (#4)

I can't get anywhere without that file it seems.
no checkpoint
(torch) ➜  One-Shot_Free-View_Neural_Talking_Head_Synthesis git:(main) ✗ python demo.py --config config/vox-256.yaml  --source_image '/home/jp/Desktop/2.jpg'  --driving_video '/home/jp/Documents/gitWorkspace/SimSwap/J11-wm.mp4'  --relative --adapt_scale --find_best_frame 



demo.py:28: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

  config = yaml.load(f)

Traceback (most recent call last):

  File "demo.py", line 282, in <module>

    generator, kp_detector, he_estimator = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, cpu=opt.cpu)

  File "demo.py", line 48, in load_checkpoints

    checkpoint = torch.load(checkpoint_path)

  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 579, in load

    with _open_file_like(f, 'rb') as opened_file:

  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like

    return _open_file(name_or_buffer, mode)

  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__

    super(_open_file, self).__init__(open(name, mode))

FileNotFoundError: [Errno 2] No such file or directory: ''


made up check point. (file doesn't exist)
(torch) ➜  One-Shot_Free-View_Neural_Talking_Head_Synthesis git:(main) ✗ python demo.py --config config/vox-256.yaml --checkpoint ./check.pt --source_image '/home/jp/Desktop/2.jpg'  --driving_video '/home/jp/Documents/gitWorkspace/SimSwap/J11-wm.mp4'  --relative --adapt_scale --find_best_frame



demo.py:28: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

  config = yaml.load(f)

Traceback (most recent call last):

  File "demo.py", line 282, in <module>

    generator, kp_detector, he_estimator = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, cpu=opt.cpu)

  File "demo.py", line 48, in load_checkpoints

    checkpoint = torch.load(checkpoint_path)

  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 579, in load

    with _open_file_like(f, 'rb') as opened_file:

  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like

    return _open_file(name_or_buffer, mode)

  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__

    super(_open_file, self).__init__(open(name, mode))

FileNotFoundError: [Errno 2] No such file or directory: './check.pt'


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
