### ISSUE TITLE
pickle.UnpicklingError when train

### ISSUE THREAD

**Issue by wl0521** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#44]
Good Day, Zhang:
I encount a problem when training:

My conda env:
torch == 1.7.1+cu110
torchvision == 0.8.2+cu110
pytorch3d == 0.6.1
python == 3.8

The Excption Information as below:

  File "OneShot/run.py", line 92, in <module>
    train(config, generator, discriminator, kp_detector, he_estimator, opt.checkpoint, log_dir, dataset, opt.device_ids)
  File "/home/theonemagic/Downloads/U_PycharmProjects/pytorch3d_root/OneShot/train.py", line 43, in train
    generator_full = GeneratorFullModel(kp_detector, he_estimator, generator, discriminator, train_params, estimate_jacobian=config['model_params']['common_params']['estimate_jacobian'])
  File "/home/theonemagic/Downloads/U_PycharmProjects/pytorch3d_root/OneShot/modules/model.py", line 257, in __init__
    hopenet_state_dict = torch.load(train_params['hopenet_snapshot'])
  File "/home/theonemagic/anaconda3/envs/python3d/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/theonemagic/anaconda3/envs/python3d/lib/python3.8/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
**_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.**

I do not know how to solve, waiting for your assistance and thanks in advance.

**Comment by zhanglonghao1992** [comment]
@wl0521 Have you downloaded hopenet_robust_alpha1.pkl and added the path to the config? Make sure that `hopenet_snapshot` in vox.yaml is correct.

**Comment by wl0521** [comment]
yes ,this step is omitted, thanks, i will try later

**Comment by KenChen701** [comment]
Hi, I encountered a similar problem when I ran demo.py:

Traceback (most recent call last):
  File "demo_test_ckpt.py", line 287, in <module>
    generator, kp_detector, he_estimator = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, gen=opt.gen, cpu=opt.cpu)
  File "demo_test_ckpt.py", line 53, in load_checkpoints
    checkpoint = torch.load(checkpoint_path)
  File "/data/gpfs/projects/punim1997/anaconda3/envs/fadm/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/data/gpfs/projects/punim1997/anaconda3/envs/fadm/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
~                                               

My conda env:
torch == 1.7.0+cu101
python == 3.6.13

Could you give me an assistant? Thank you so much!
