### ISSUE TITLE
Can't import circle from skimage.draw

### ISSUE THREAD

**Issue by oo92** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#49]
```
    from skimage.draw import circle
ImportError: cannot import name 'circle' from 'skimage.draw' (/home/onur/.local/lib/python3.9/site-packages/skimage/draw/__init__.py)
```

I've changed the function to `skimage.draw.disk()` and now I am getting this error. `skimage.draw.ellipse()` returns the same error:

```
14it [00:01, 12.32it/s]/home/onur/.local/lib/python3.9/site-packages/face_alignment/api.py:144: UserWarning: No faces were detected.
  warnings.warn("No faces were detected.")
14it [00:01, 11.98it/s]
Traceback (most recent call last):
  File "/home/onur/git-repos/One-Shot_Free-View_Neural_Talking_Head_Synthesis/demo.py", line 291, in <module>
    i = opt.best_frame if opt.best_frame is not None else find_best_frame(source_image, driving_video, cpu=opt.cpu)
  File "/home/onur/git-repos/One-Shot_Free-View_Neural_Talking_Head_Synthesis/demo.py", line 228, in find_best_frame
    kp_driving = fa.get_landmarks(255 * image)[0]
TypeError: 'NoneType' object is not subscriptable
```

The input image is a very clear selfie and the video is just a 4K 10s clip of Homelander from The Boys.

**Comment by muzy06038** [comment]
Use scikit-image==0.18.0
