### ISSUE TITLE
ImageIO plugin ValueError

### ISSUE THREAD

**Issue by oo92** [zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis#50]
```
onur@onur-XPS-15-7590:~/git-repos/One-Shot_Free-View_Neural_Talking_Head_Synthesis$ python3 demo.py --config config/vox-256-spade.yaml --checkpoint 00000189-checkpoint.pth.tar --source_image example-images/me.jpg --driving_video crop.mp4 --relative --adapt_scale --find_best_frame --free_view --yaw 20 --pitch 0 --roll 0
/home/onur/git-repos/One-Shot_Free-View_Neural_Talking_Head_Synthesis/demo.py:24: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
/home/onur/.local/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/onur/git-repos/One-Shot_Free-View_Neural_Talking_Head_Synthesis/demo.py:286: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
estimate jacobian: False
179it [00:15, 11.69it/s]
Best frame: 38
/home/onur/git-repos/One-Shot_Free-View_Neural_Talking_Head_Synthesis/demo.py:71: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  pred = F.softmax(pred)
  0%|                                                                                                                | 0/141 [00:00<?, ?it/s]/home/onur/.local/lib/python3.9/site-packages/torch/nn/functional.py:4003: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/home/onur/.local/lib/python3.9/site-packages/torch/nn/functional.py:1806: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 141/141 [01:25<00:00,  1.64it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 39/39 [00:25<00:00,  1.54it/s]
Traceback (most recent call last):
  File "/home/onur/git-repos/One-Shot_Free-View_Neural_Talking_Head_Synthesis/demo.py", line 300, in <module>
    imageio.mimsave(opt.result_video, [img_as_ubyte(frame) for frame in predictions], fps=fps)
  File "/home/onur/.local/lib/python3.9/site-packages/imageio/core/functions.py", line 283, in mimwrite
    with imopen(uri, "wI", plugin=format) as file:
  File "/home/onur/.local/lib/python3.9/site-packages/imageio/core/imopen.py", line 223, in imopen
    raise err_type(err_msg)
ValueError: ImageIO does not generally support reading folders. Limited support may be available via specific plugins. Specify the plugin explicitly using the `plugin` kwarg, e.g. `plugin='DICOM'`
``

**Comment by muzy06038** [comment]
RUN : python3 demo.py --config config/vox-256-spade.yaml --checkpoint 00000189-checkpoint.pth.tar --source_image example-images/me.jpg --driving_video crop.mp4 --relative --adapt_scale --find_best_frame --free_view --yaw 20 --pitch 0 --roll 0 **--result_video result.mp4**
